// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://gvryyqhtaempzgrbinrj.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cnl5cWh0YWVtcHpncmJpbnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwNDAwMTcsImV4cCI6MjA0ODYxNjAxN30.7Jy5slMEcPziNvyk44oXUFWDkjXknTPwrSXw3YuBsKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);